/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2015-12-08 10:37:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class appointment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"validation.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"hams.css\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>hams</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div style=\" margin-top: 45px; margin-right:45px ;float:right\"><b>\r\n");
      out.write("      \t");
 
			String username = (String)request.getSession().getAttribute("name"); 
			out.println("Welcome "+username);
		
      out.write("<br>\r\n");
      out.write("      \t<a href=\"LogoutServlet\">Logout</a>\r\n");
      out.write("</b></div>\r\n");
      out.write("\r\n");
      out.write("<img src = \"images/HAMSLogo.jpg\" alt=\"hamslogo\" id=\"img1\" style=\" margin-left: 45px; \"/>\r\n");
 
			Boolean admin_check = (Boolean)request.getSession().getAttribute("hide_report");
			if(admin_check){
			
      out.write("\t\r\n");
      out.write("\t\t\t\t<div style=\"margin-left: 45px; margin-top: 50px; position: absolute;\">\r\n");
      out.write("\t\t\t\t<b>\t<a href=\"generateReport.jsp\" >Appointment Report</a></b>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
 
	        admin_check = true ;		}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"margin-left: 45px; margin-top: 75px; position: absolute;\">\r\n");
      out.write("\t\t\t\t<b>\t<a href=\"DoctorDetail.jsp\" >Enter Doctor Detail</a></b>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<h4 style= \"text-align:center\">\r\n");

	String message = (String)request.getSession().getAttribute("message_response");
	if( message != null)
	{
		out.println(message);
	} 
	session.setAttribute("message_response", "");

      out.write("\r\n");
      out.write("\t</h4>\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("\r\n");
      out.write("<div id=\"login-overlay\" class=\"modal-dialog\"  style=\"width:800px;  \">\r\n");
      out.write("     <div class=\"modal-content\" id=\"modal-content\" >\r\n");
      out.write("          <div class=\"modal-header\" >\r\n");
      out.write("\t\t\t\t<h1>HAMS</h1>\r\n");
      out.write("\t\t\t\t\t<p><b><font size=5>Clinic Appointment</font></b></p>\r\n");
      out.write("\t\t\t\t\t<p><font size=1><b><sup>*</sup></b> Required Fields</font></p>\r\n");
      out.write("<form name=\"myForm\" action=\"AppointmentServlet\" method=\"post\"  onsubmit=\"return validate()\" >\r\n");
      out.write(" \t<div class=\"form-group\">\r\n");
      out.write("<table >\r\n");
      out.write(" <tbody>\r\n");
      out.write(" \t\r\n");
      out.write(" \t <tr class=\"row1\">\r\n");
      out.write("\t \t <td><b>Patient mobile Number: <sup>*</sup></b> </td>\r\n");
      out.write("\t \t <td><input type=\"text\" id=\"patient_mobile_number\" name=\"patient_mobile_number\"  size=50 maxlength=20  placeholder=\"mobile_number\" title=\"Please enter your patient mobile number\"/></td>\r\n");
      out.write("\t </tr>\r\n");
      out.write(" \t\r\n");
      out.write("\t <tr class=\"row2\">\r\n");
      out.write("\t \t <td><b>Patient Name: <sup>*</sup></b> </td>\r\n");
      out.write("\t \t <td><input type=\"text\" id=\"patient_name\" name=\"patient_name\"  size=50 maxlength=5000 placeholder=\"patient_name\" title=\"Please enter patient name\"/></td>\r\n");
      out.write("\t </tr> \r\n");
      out.write("\t \r\n");
      out.write("\t <tr class=\"row3\"> \r\n");
      out.write("\t \t<td><b>Clinic Detail: <sup>*</sup></b> </td>\r\n");
      out.write("\t \t<td><input type=\"text\" id=\"clinic_detail\" name=\"clinic_detail\"  size=50 maxlength=5000  placeholder=\"clinic detail\" title=\"Please enter clinic detail\"/></td>\r\n");
      out.write("\t </tr> \r\n");
      out.write("\t \r\n");
      out.write("\t <tr class=\"row4\"> \r\n");
      out.write("\t \t<td style=\"padding-right: 10px\"><b>Approx Appointment Time: <sup>*</sup></b> </td> \r\n");
      out.write("\t \t<td><input type=\"text\" id=\"time\" name=\"time\"  size=50 maxlength=5000 placeholder=\"time\" title=\"Please enter time\"/></td> \r\n");
      out.write("\t </tr>\r\n");
      out.write("\t \r\n");
      out.write("\t <tr class=\"row5\"> \r\n");
      out.write("\t \t<td style=\"padding-right: 10px\"><b>Appointment Date: <sup>*</sup></b> </td> \r\n");
      out.write("\t \t<td><input type=\"date\" id=\"appointment_date\" name=\"appointment_date\"   placeholder=\"appointment_date\" title=\"Please enter appointment date\" required ></td> \r\n");
      out.write("\t </tr>\r\n");
      out.write("\t \r\n");
      out.write(" </tbody>\t \r\n");
      out.write("\t  \r\n");
      out.write("</table> \r\n");
      out.write("\t<br /><input type=\"submit\" name=\"submit\" value=\"submit\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
