/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2015-12-09 05:15:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DoctorDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"hams.css\">\r\n");
      out.write("<title>Hams</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link href=\"assets/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"assets/css/bootstrap-responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h5 style=\" margin-top: 45px; margin-right:45px ;float:right\"><b>\r\n");
      out.write("      \t");
 
			String username = (String)request.getSession().getAttribute("name"); 
			out.println("Welcome "+username);
		
      out.write("<br>\r\n");
      out.write("      \t<a href=\"LogoutServlet\">Logout</a>\r\n");
      out.write("</b></h5>\r\n");
      out.write("\r\n");
      out.write("<img src = \"images/HAMSLogo.jpg\" alt=\"hamslogo\" id=\"img1\" style=\" margin-left: 45px; \"/>\r\n");
 
			Boolean admin_check = (Boolean)request.getSession().getAttribute("hide_report");
			if(admin_check){
			
      out.write("\t\r\n");
      out.write("\t\t\t\t<div style=\"margin-left: 45px; margin-top: 30px; position: absolute;\">\r\n");
      out.write("\t\t\t\t<b>\t<a href=\"generateReport.jsp\" >Appointment Report</a></b>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t");
 
			}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"margin-left: 45px; margin-top: 10px; \"><b>\r\n");
      out.write("\t <a href=\"appointment.jsp\">home</a></b>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h4 style= \"text-align:center ;\">\r\n");

	String message = (String)request.getSession().getAttribute("data_saved");
	if( message != null)
	{
		out.println(message);
	} 
	session.setAttribute("data_saved", "");

      out.write("\r\n");
      out.write("\t</h4>\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("\r\n");
      out.write("<div id=\"login-overlay\" class=\"modal-dialog\"  style=\"width:960px; \">\r\n");
      out.write("     <div class=\"modal-content\" id=\"modal-content\" >\r\n");
      out.write("  \r\n");
      out.write("\t\t\t\t<h1>HAMS</h1>\r\n");
      out.write("\t\t\t\t\t<p><b><font size=5>Doctor Registration Form</font></b></p>\r\n");
      out.write("\t\t\t\t\t<p><font size=1><b><sup>*</sup></b> Required Fields</font></p>\r\n");
      out.write("<form name=\"myForm\" action=\"DoctorRegistrationServlet\" method=\"post\" id=\"myForm\">\r\n");
      out.write(" \t<div class=\"form-group\">\r\n");
      out.write("<table >\r\n");
      out.write(" <tbody>\r\n");
      out.write(" \t\r\n");
      out.write(" \t <tr class=\"row1\" >\r\n");
      out.write("\t \t <td><b>Clinic Name: <sup>*</sup></b> </td>\r\n");
      out.write("\t \t <td style=\"padding-right: 10px\"><input type=\"text\" id=\"clinic_name\" name=\"clinic_name\"  size=32 maxlength=5000  placeholder=\"clinic_name\" title=\"Please enter your Clinic Name\" required/></td>\r\n");
      out.write("\t \t \r\n");
      out.write("\t \t<td style=\"padding-right: 10px\"><b>Price Quota: <sup>*</sup></b> </td> \r\n");
      out.write("\t \t<td><input type=\"text\" id=\"price_quota\" name=\"price_quota\"  size=32 placeholder=\"price_quota\" title=\"Please enter Price Quota\" required ></td> \r\n");
      out.write("\t \t \r\n");
      out.write("\t </tr>\r\n");
      out.write(" \t\r\n");
      out.write("\t <tr class=\"row2\">\r\n");
      out.write("\t \t <td><b>Clinic Address: <sup>*</sup></b> </td>\r\n");
      out.write("\t \t <td><input type=\"text\" id=\"address\" name=\"address\"  size=32 maxlength=5000 placeholder=\"clinic_address\" title=\"Please enter Clinic Address\" required/></td>\r\n");
      out.write("\t \t\r\n");
      out.write("\t \t <td style=\"padding-right: 10px\"><b>Agreement Mode: <sup>*</sup></b> </td> \r\n");
      out.write("\t \t <td><select name=\"agreement_mode\" type=\"text\" id=\"agreement_mode\" required>\r\n");
      out.write("  \t\t\t<option value=\"Per Patient Visit\">Per Patient Visit</option>\r\n");
      out.write("  \t\t\t<option value=\"Monthly\">Monthly</option>\r\n");
      out.write("  \t\t\t<option value=\"weekly\">weekly</option>  \t\t\t\r\n");
      out.write("\t\t  </select>\r\n");
      out.write("\t\t </td>\r\n");
      out.write("\t \t\r\n");
      out.write("\t </tr> \r\n");
      out.write("\t\r\n");
      out.write("\t \r\n");
      out.write("\t <tr class=\"row3\"> \r\n");
      out.write("\t \t<td style=\"padding-right: 10px\"><b>Authorised Doctor Name: <sup>*</sup></b> </td> \r\n");
      out.write("\t \t<td><input type=\"text\" id=\"authorised_doctor_name\" name=\"authorised_doctor_name\"   size=32 maxlength=5000 placeholder=\"authorised_doctor_name\" title=\"Please enter Authorised Doctor Name\" required ></td> \r\n");
      out.write("\t \t\r\n");
      out.write("\t \t<td style=\"padding-right: 10px\"><b>Payment Cycle: <sup>*</sup></b> </td> \r\n");
      out.write("\t \t<td><select name=\"payment_cycle\" type=\"text\" id=\"payment_cycle\" title=\"Please enter Payment Cycle\" required>\r\n");
      out.write("  \t\t\t<option value=\"weekly\">Weekly</option>\r\n");
      out.write("  \t\t\t<option value=\"bi_weekly\">Bi-Weekly</option>  \r\n");
      out.write("  \t\t\t<option value=\"Monthly\">Monthly</option>  \t\t\t\r\n");
      out.write("\t\t  </select>\r\n");
      out.write("\t\t </td>\r\n");
      out.write("\t </tr> \r\n");
      out.write("\t \r\n");
      out.write("\t <tr class=\"row4\"> \r\n");
      out.write("\t \t<td style=\"padding-right: 10px\"><b>Doctor Specialization: <sup>*</sup></b> </td> \r\n");
      out.write("\t    <td><input type=\"text\" id=\"doctor_specialization\" name=\"doctor_specialization\"  size=32 maxlength=5000 placeholder=\"doctor_specialization\" title=\"Please enter Doctor Specialization\" required/></td>  \r\n");
      out.write("\t \t\r\n");
      out.write("\t\t<td style=\"padding-right: 10px\"><b>Agreement Date:<sup>*</sup></b> </td> \r\n");
      out.write("\t \t<td><input type=\"date\" id=\"agreement_date\" name=\"agreement_date\"  size=25 placeholder=\"agreement_date\" title=\"Please enter Agreement Date\" required ></td> \t \t \t\r\n");
      out.write("\t </tr>\r\n");
      out.write("\t \r\n");
      out.write("\t <tr class=\"row5\"> \r\n");
      out.write("\t \r\n");
      out.write("\t \t\r\n");
      out.write("\t \t<td style=\"padding-right: 10px\"><b>Doctor Experience: <sup>*</sup></b> </td> \r\n");
      out.write("\t \t <td><select name=\"doctor_experience\" type=\"text\" id=\"doctor_experience\" required>\r\n");
      out.write("  \t\t\t<option value=\"0\">0</option>\r\n");
      out.write("  \t\t\t<option value=\"1\">1</option>\r\n");
      out.write("  \t\t\t<option value=\"2\">2</option>\r\n");
      out.write("  \t\t\t<option value=\"3\">3</option>\r\n");
      out.write("  \t\t\t<option value=\"4\">4</option>\r\n");
      out.write("  \t\t\t<option value=\"5\">5</option>\r\n");
      out.write("  \t\t\t<option value=\"6\">6</option>\r\n");
      out.write("  \t\t\t<option value=\"7\">7</option>\r\n");
      out.write("  \t\t\t<option value=\"8\">8</option>\r\n");
      out.write("  \t\t\t<option value=\"9\">9</option>\r\n");
      out.write("  \t\t\t<option value=\"10\">10</option>\r\n");
      out.write("  \t\t\t<option value=\"11\">11</option>\r\n");
      out.write("  \t\t\t<option value=\"12\">12</option>\r\n");
      out.write("  \t\t\t<option value=\"13\">13</option>\r\n");
      out.write("  \t\t\t<option value=\"14\">14</option>\r\n");
      out.write("  \t\t\t<option value=\"15\">15</option>\r\n");
      out.write("  \t\t\t<option value=\"16\">16</option>\r\n");
      out.write("  \t\t\t<option value=\"17\">17</option>\r\n");
      out.write("  \t\t\t<option value=\"18\">18</option>\r\n");
      out.write("  \t\t\t<option value=\"19\">19</option>\r\n");
      out.write("  \t\t\t<option value=\"20\">20</option>\r\n");
      out.write("  \t\t\t<option value=\"21\">21</option>\r\n");
      out.write("  \t\t\t<option value=\"22\">22</option>\r\n");
      out.write("  \t\t\t<option value=\"23\">23</option>\r\n");
      out.write("  \t\t\t<option value=\"24\">24</option>\r\n");
      out.write("  \t\t\t<option value=\"25\">25</option>\r\n");
      out.write("  \t\t\t<option value=\"26\">26</option>\r\n");
      out.write("  \t\t\t<option value=\"27\">27</option>\r\n");
      out.write("  \t\t\t<option value=\"28\">28</option>\r\n");
      out.write("  \t\t\t<option value=\"29\">29</option>\r\n");
      out.write("  \t\t\t<option value=\"30\">30</option>\r\n");
      out.write("\t\t  </select>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t \t\r\n");
      out.write("\t \t<td style=\"padding-right: 10px\"><b>Emergency Contact number: </b> </td> \r\n");
      out.write("\t \t<td><input type=\"text\" id=\"emergency_contact_number\" name=\"emergency_contact_number\"  size=25 placeholder=\"emergency_contact_number\" title=\"Please enter Emergency Contact number\"  ></td> \t \t\r\n");
      out.write("\t \t\r\n");
      out.write("\t </tr>\r\n");
      out.write("\t \r\n");
      out.write("\t <tr class=\"row6\"> \r\n");
      out.write("\t \t<td style=\"padding-right: 10px\"><b>Service Timing: <sup>*</sup></b> </td> \r\n");
      out.write("\t \t<td><input type=\"text\" id=\"doctor_experience\" name=\"doctor_experience\"  size=32 maxlength=5000 placeholder=\"doctor_experience\" title=\"Please enter Doctor Experience\" required/></td>\r\n");
      out.write("\t \t\r\n");
      out.write("\t\t<td style=\"padding-right: 10px\"><b>Secondary Contact number: </b> </td> \r\n");
      out.write("\t \t<td><input type=\"text\" id=\"secondary_contact_number\" name=\"secondary_contact_number\"  size=25 placeholder=\"secondary_contact_number\" title=\"Please enter Secondary Contact number\"  ></td> \t \t\r\n");
      out.write("\t </tr>\r\n");
      out.write("\t \r\n");
      out.write("\t <tr class=\"row7\"> \r\n");
      out.write("\t \t <td><b>Contact number: <sup>*</sup></b> </td>\r\n");
      out.write("\t \t<td><input type=\"text\" id=\"contact_number\" name=\"contact_number\"  size=32 maxlength=5000  placeholder=\"contact_number\" title=\"Please enter Contact Number\" required/></td>\r\n");
      out.write("\t \t\t\r\n");
      out.write("\t \t<td style=\"padding-right: 10px\"><b>Doctor OnBoard: </b> </td> \r\n");
      out.write("\t \t<td><input type=\"checkbox\" id=\"onboard\" name=\"onboard\"  size=32 placeholder=\"onboard\"  /></td>\r\n");
      out.write("\t </tr>\r\n");
      out.write("\t \r\n");
      out.write("\t <tr class=\"row8\">\r\n");
      out.write("\t \t<td style=\"padding-right: 10px\"><b>Email: </b> </td> \r\n");
      out.write("\t \t<td><input type=\"text\" id=\"email\" name=\"email\"  size=32 maxlength=5000 placeholder=\"email\" title=\"Please enter email\" /></td>\r\n");
      out.write("\t \t\r\n");
      out.write("\t \t\r\n");
      out.write("\t </tr>\r\n");
      out.write("\t </tr>\r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("</tbody>\t \r\n");
      out.write("\t  \r\n");
      out.write("</table> \r\n");
      out.write("\t<br /><input type=\"submit\" name=\"submit\" value=\"submit\" />\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
