/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2015-12-07 13:40:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"hams.css\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\"/>\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("img {\r\n");
      out.write("\t\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tbottom: 100px; \r\n");
      out.write("    height: 150px; \r\n");
      out.write("    width: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");

        if(session.isNew())
            {
            session = request.getSession();
            String s = request.getParameter("login");
            session.setAttribute("first", s);
            }
 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id=\"login-overlay\" class=\"modal-dialog\" style=\"margin-top:100px;\">\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("          <div class=\"modal-header\">\r\n");
      out.write("              <h4 class=\"modal-title\" id=\"myModalLabel\"><b>Login to Hams Patient Appointment </b></h4> \r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"modal-body\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-xs-6\">\r\n");
      out.write("                      <div class=\"well\">\r\n");
      out.write("                          <form id=\"loginForm\" method=\"POST\" action=\"LoginServlet\">\r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                  <label for=\"username\" class=\"control-label\">Username</label>\r\n");
      out.write("                                  <input type=\"text\" class=\"form-control\" name=\"name\" value=\"\"  title=\"Please enter your username\" placeholder=\"username\">\r\n");
      out.write("                                  <span class=\"help-block\"></span>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              \r\n");
      out.write("                              <div class=\"form-group\">\r\n");
      out.write("                                  <label for=\"password\" class=\"control-label\">Password</label>\r\n");
      out.write("                                  <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"password\" value=\"\" title=\"Please enter your password\">\r\n");
      out.write("                                  <span class=\"help-block\"></span>\r\n");
      out.write("                              </div>\r\n");
      out.write("                              \r\n");
      out.write("                              <button type=\"submit\" value=\"login\" name=\"submit\" class=\"btn btn-success btn-block\">Login</button>\r\n");
      out.write("                          </form>\r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("                  <div class=\"col-xs-6\">\r\n");
      out.write("                      <p class=\"lead\">Login now for <span class=\"text-success\">Patient Appointment</span></p>\r\n");
      out.write("                      \r\n");
      out.write("                      <img src = \"images/HAMSLogo.jpg\" alt=\"hamslogo\" /> \r\n");
      out.write("                      \r\n");
      out.write("                  </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                          \r\n");
      out.write("      </div>\r\n");
      out.write("</div>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
