/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2015-12-08 09:42:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class message_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script src=\"validation.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function myFunction(){\r\n");
      out.write("\tdocument.getElementById(\"wait_message\").innerHTML = \"message is being sent please wait\";\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function myFunction1(){\r\n");
      out.write("\tdocument.getElementById(\"wait_message\").innerHTML = \"please wait edit page is loading\";\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"hams.css\">\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\" />\r\n");
      out.write("\r\n");
      out.write("<title>hams</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#ok {\r\n");
      out.write("    width: 200px  ;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rela {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    left: 24px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td:nth-of-type(2) {\r\n");
      out.write("   padding-right: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#wait_message\r\n");
      out.write("{\r\n");
      out.write("    color:black;\r\n");
      out.write("    font-weight:bold;\r\n");
      out.write("    margin:0px 0px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\" margin-top: 45px; margin-right:45px\"><b>\r\n");
      out.write("      <span style=\"float:right\">\r\n");
      out.write("      \t");
 
			String username = (String)request.getSession().getAttribute("name"); 
			out.println("Welcome "+username);
		
      out.write("<br>\r\n");
      out.write("\t\t<a href=\"LogoutServlet\">Logout</a>\r\n");
      out.write("      </span>\r\n");
      out.write("\r\n");
      out.write("</b></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<img src = \"images/HAMSLogo.jpg\" alt=\"hamslogo\" id=\"img1\" style=\" margin-left: 45px; \"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"margin-left: 45px; margin-top: 10px; position: absolute;  \"><b>\r\n");
      out.write("\t <a href=\"appointment.jsp\">home</a></b>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"rela\">\r\n");
      out.write("<h3>\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String message = (String)request.getSession().getAttribute("message_response");
	if( message != null)
	{
		out.println(message);
	} 
	session.setAttribute("message_response", "");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</h3>\r\n");
      out.write("</div>\r\n");
      out.write("<center>\r\n");
      out.write("\r\n");
      out.write("<div id=\"wait_message\" > </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"login-overlay\" class=\"modal-dialog\" style=\"width:800px;\">\r\n");
      out.write("     <div class=\"modal-content\" >\r\n");
      out.write("          <div class=\"modal-header\" >\r\n");
      out.write("<div >\r\n");
      out.write("\t<b>\r\n");
      out.write("\t\t");
 
			StringBuilder message1 = (StringBuilder)request.getSession().getAttribute("message"); 
			out.println(message1);	
		
      out.write("\r\n");
      out.write("\t</b>\r\n");
      out.write("</div>\t\r\n");
      out.write("\r\n");
      out.write("<form action=\"ConfirmAppointmentServlet\" method=\"post\" style=\"margin-top:20px;\">\r\n");
      out.write("<div class=\"form-group\">\r\n");
      out.write("<table >\r\n");
      out.write(" <tbody>\r\n");
      out.write("\t<tr class=\"row1\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<td style=\"padding-right: 10px\"><b>to save and send message </b></td>\r\n");
      out.write("\t\t<td id=\"ok\" onclick=\"myFunction()\" ><input type=\"submit\" name=\"act\" value=\"ok\" /></td>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<td style=\"padding-right: 10px\"><b>to edit message </b></td>\r\n");
      out.write("\t\t<td id=\"edit\" onclick=\"myFunction1()\" ><input type=\"submit\" name=\"act\" value=\"edit\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</center>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
